version: "2.4"
services:
  example:
    restart: unless-stopped
    build: .
    pids_limit: 256
    mem_limit: 64M
    cpus: 0.5
    volumes:
      - ./notes:/app/notes
    ports:
      - 1337:5000

  cleaner:
    image: c4tbuts4d/dedcleaner:latest
    restart: unless-stopped
    volumes:
      - "./notes:/notes"
    environment:
      - DELETE_AFTER=30m
      - SLEEP=30m
      - DIRS=/notes
