version: '2.4'

services:
  virush:
    build: service
    cpus: 2
    pids_limit: 65536
    mem_limit: 1G
    restart: unless-stopped
    stop_grace_period: 3s
    volumes:
      - "keys:/tmp/keys_directory"
      - "storage:/tmp/storage_directory"

  nginx:
    image: nginx:latest
    cpus: 1
    pids_limit: 512
    mem_limit: 512M
    restart: unless-stopped
    stop_grace_period: 3s
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "17171:80"
    depends_on:
      - virush
      - cleaner

  cleaner:
    build: cleaner
    cpus: 1
    pids_limit: 128
    mem_limit: 128M
    restart: unless-stopped
    stop_grace_period: 3s
    volumes:
      - "keys:/tmp/keys_directory"
      - "storage:/tmp/storage_directory"
    depends_on:
      - virush

volumes:
  keys:
  storage:
