version: '2.4'
services:
  backend:
    build: .
    cpus: 1
    pids_limit: 256
    mem_limit: 1024m
    volumes:
      - "./data/uploads:/uploads"
    depends_on:
      - celery
      - redis
    restart: unless-stopped
  celery:
    build: .
    entrypoint: "celery -A main.celery_app worker -l info"
    cpus: 2
    pids_limit: 1024
    mem_limit: 512m
    restart: unless-stopped
    volumes:
      - "./data/uploads:/uploads"
    depends_on:
      - redis
  nginx:
    image: nginx:1.18.0-alpine
    restart: unless-stopped
    volumes:
      - ./front/app.conf:/etc/nginx/conf.d/default.conf
      - ./front/proxy_params:/etc/nginx/proxy_params
      - ./front/build:/front/build
      - ./docs:/front/docs
    depends_on:
      - backend
      - celery
    ports:
      - "8000:80"
  redis:
    image: redis:alpine
    restart: unless-stopped
    mem_limit: 512m
    volumes:
      - "./data/redis:/data"
  cleaner:
    image: c4tbuts4d/dedcleaner:latest
    restart: unless-stopped
    volumes:
      - "./data/uploads:/uploads"
    environment:
      - DELETE_AFTER=60m
      - SLEEP=60m
      - DIRS=/uploads
    depends_on:
      - backend